<<<<<<< HEAD
# Generated by Django 3.1 on 2021-10-14 04:18
=======
# Generated by Django 2.2.10 on 2021-09-12 20:27
>>>>>>> parent of 0a4844d (files with new templates)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='agent name', max_length=150)),
                ('ssdc_number', models.CharField(default='agent ssdc number', max_length=100)),
<<<<<<< HEAD
                ('installation', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('Pay Bill', 'Pay Bill'), ('Till Number', 'Till Number')], default='m-pesa', max_length=200)),
                ('till_or_paybill_number', models.CharField(default='000000000', max_length=20)),
                ('acc_number', models.CharField(default='123456789', max_length=200)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
=======
                ('isp_name', models.CharField(default='isp name', max_length=100)),
                ('monthly_subscription', models.IntegerField(default='monthly subscription')),
                ('due_date', models.DateField(default='due date')),
                ('approved', models.BooleanField(default='true or false')),
>>>>>>> parent of 0a4844d (files with new templates)
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tl name', max_length=150)),
                ('ssdc_number', models.CharField(default='tl ssdc number', max_length=100)),
<<<<<<< HEAD
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isp_name', models.CharField(default='isp name', max_length=100)),
                ('monthly_subscription', models.IntegerField(default='monthly subscription')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices')),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Payment Pending', 'Payment Pending'), ('Not Paid', 'Not Paid')], default='Payment Pending', max_length=100)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('reason_declined', models.TextField(blank=True, default='The invoice was accepted!', null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.project'),
        ),
        migrations.AddField(
            model_name='agent',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teamleader'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
=======
                ('project', models.CharField(default='project name', max_length=60)),
            ],
        ),
>>>>>>> parent of 0a4844d (files with new templates)
    ]
