# Generated by Django 2.2.10 on 2021-09-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='agent name', max_length=150)),
                ('ssdc_number', models.CharField(default='agent ssdc number', max_length=100)),
                ('isp_name', models.CharField(default='isp name', max_length=100)),
                ('monthly_subscription', models.IntegerField(default='monthly subscription')),
                ('due_date', models.DateField(default='due date')),
                ('approved', models.BooleanField(default='true or false')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tl name', max_length=150)),
                ('ssdc_number', models.CharField(default='tl ssdc number', max_length=100)),
                ('project', models.CharField(default='project name', max_length=60)),
            ],
        ),
    ]
