# Generated by Django 2.2.10 on 2021-09-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
