# Generated by Django 3.1 on 2021-09-20 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210919_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Payment Pending', 'Payment Pending'), ('Not Paid', 'Not Paid')], default='Payment Pending', max_length=100),
        ),
    ]
