# Generated by Django 3.1 on 2021-09-20 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210920_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleader',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
