# Generated by Django 3.1 on 2021-09-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_invoice_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='project',
        ),
    ]
