# Generated by Django 3.1 on 2021-09-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_invoice_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
