# Generated by Django 3.1 on 2021-09-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_invoice_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='installation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teamleader'),
        ),
    ]
