# Generated by Django 3.1 on 2021-09-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210927_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='payment_method',
            field=models.CharField(choices=[('m-pesa', 'm-pesa'), ('bank', 'bank'), ('airtel money', 'airtel money'), ('t-kash', 't-kash'), ('paypal', 'paypal')], default='m-pesa', max_length=200),
        ),
    ]
