# Generated by Django 3.1 on 2021-10-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_agent_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='acc_number',
            field=models.CharField(default='123456789', max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='till_or_paybill_number',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='payment_method',
            field=models.CharField(choices=[('Pay Bill', 'Pay Bill'), ('Till Number', 'Till Number')], default='m-pesa', max_length=200),
        ),
    ]
