# Generated by Django 3.1 on 2021-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211006_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reason_declined',
            field=models.TextField(blank=True, default='The invoice was accepted!', null=True),
        ),
    ]
